### ISSUE TITLE
Disorder.Aeson.Time.genTime generates "Julian" dates earlier than 1858AD.

### ISSUE THREAD

**Issue by damncabbage** [ambiata/disorder.hs#116]
> The Modified Julian Day is a standard count of days, with zero being the day 1858-11-17.

`genTime` has `fmap ModifiedJulianDay arbitrary`, which will give us negative integer values. I'm not sure a negative "epoch" value makes sense.

Should I PR something that adds an `abs` with the `arbitrary`?

**Comment by jystic** [comment]
I'm not sure that generating negative numbers is an issue per se. The epoch is just an arbitrary point in time, having negative values is fine I think. If you pretty print the negative number you'll still get a valid date.

Fwiw, Ivory allows dates in the range `1600-03-01` - `3000-12-31`.

**Comment by damncabbage** [comment]
Got it. Thanks. :)
